name: mlc
description: Measuring Learning Concentration Flutter App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 原有，保留
  percent_indicator: ^4.2.3
  http: ^1.1.0
  fl_chart: ^0.66.0

  # 新版本
  flutter_pdfview: ^1.3.2
  camera: ^0.10.5+9
  file_selector: ^1.1.0
  google_generative_ai: ^0.4.6
  supabase_flutter: ^2.5.1

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  permission_handler: ^11.3.0
  file_picker: ^8.0.0+1
  image: ^4.1.7
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#102C57"
  adaptive_icon_foreground: "assets/logo.png"